### PR TITLE
pass Modal prop zIndexOffset also to BackDrop

### LINKED ISSUE #2246: Modal prop zIndexOffset is not passed to BackDrop component
**Describe the bug**
I would like to show a `Modal` on top of an [`amsterdam-react-maps`](https://github.com/Amsterdam/amsterdam-react-maps) Map. The Map has a default z-index of 400. The ASC Modal and accompanying `BackDrop` have a default z-index of resp. 21 and 20. So, to display the Modal and BackDrop on top of the Map, I set the `zIndexOffset` prop of the Modal to e.g 500. The `zIndexOffset` is applied to the Modal, but unfortunately not passed to the BackDrop component. 

**To Reproduce**
1. when rendering a Modal, e.g:
```js
import { Input, Modal, Paragraph } from '@amsterdam/asc-ui'

<Modal
  aria-labelledby="modal"
  open={true}
  zIndexOffset={500}
>
  <div style={{ display: 'block', padding: '0 15px', margin: '15px 0' }}>
    <Paragraph>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      Architecto, quisquam!
    </Paragraph>
    <Input />
  </div>
</Modal>
```
2. Open dev tools of the browser and see that: 1) Modal has a z-index of 521 and 2) BackDrop has a z-index of 20 (instead of 520).

**Expected behavior**
I would expect the BackDrop to inherit the `zIndexOffset` of the Modal.

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser: Firefox
 - Version: 102.0
 - React: 17.0.2
 - @amsterdam/asc-ui: 0.36.0

### PR DESCRIPTION
**Pull request by sidneygijzen**
Hi,

Took a stab at issue 2246. If any changes are needed, please let me know :slightly_smiling_face: 

Before opening a pull request, please ensure:

- [x] You have been following the guidelines, written in the [README](../blob/main/docs/CONTRIBUTING.md#user-content-conventions-and-rules) file
- [x] Your code has the necessary tests written
- [x] You have updated the [CHANGELOG.md unreleased sections](../blob/main/CHANGELOG.md#muser-content-unreleased)

Fixes #2246

### CODE REVIEW

File: packages/asc-ui/src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -81,7 +81,11 @@ function Modal({
           }
         : {})}
     >
-      <BackDrop backdropOpacity={backdropOpacity} onClick={handleClose} />
+      <BackDrop
+        backdropOpacity={backdropOpacity}
+        onClick={handleClose}
+        {...otherProps}
```
Comment (alimpens) [inline packages/asc-ui/src/components/Modal/Modal.tsx:87]: Passing all other props to `BackDrop` might cause issues. If you overwrite the style of the `Modal` component for example, this style overwrite would affect both `ModalStyle` and `BackDrop`. I'd pass `zIndexOffset` explicitly to both `BackDrop` and `ModalStyle`

Comment (sidneygijzen) [reply packages/asc-ui/src/components/Modal/Modal.tsx:87]: Thanks for the feedback. I will update the PR accordingly.

**Review by alimpens — APPROVED** [review]
